apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service:5432/weather"
  WEATHER_FILE_BASE_PATH: "/app/data"
  WEATHER_API_BASE_URL: "http://host.docker.internal:8081"